services:
 web:
   build: .
   working_dir: /data
   command: python form.py
   links:
    - db
   volumes:
    - .:/data
   ports:
    - "5008:5008"

 db:
  image: postgres:9.3
  environment:
   - POSTGRES_USER=sis_web
   - POSTGRES_PASSWORD=123
  ports:
   - "5008:5008"
